### ISSUE TITLE
TODO: push messages

### ISSUE THREAD

**Issue by ArtrenH** [ArtrenH/VPlan_Website#14]
possibilities: dedicated app, rss feed
note: we need customised plans first

**Comment by OfficialFreak** [comment]
Push Messages on:
- Changes regarding the user

more possible solutions:
- Using the Push API (IOS excluded) https://developer.mozilla.org/en-US/docs/Web/API/Push_API?retiredLocale=de
- IOS alternative: https://stackoverflow.com/questions/63819485/sending-push-notifications-to-ios-from-pwa
