### ISSUE TITLE
`/mobil/_phpmob/vpdir.php` endpoint broken

### ISSUE THREAD

**Issue by Belissimo-T** [ArtrenH/VPlan_Website#28]
... I think, it doesn't work anymore.

The test school (https://stundenplan24.de/10000000/mobil/_phpmob/vpdir.php) returns just a `1`.

**Comment by ArtrenH** [comment]
I think it never returned anything useful but it exists and is used by the App for some reason.

**Comment by Belissimo-T** [comment]
I just recorded all network traffic used by the VPMobil24 app. It also uses this domain:
https://www.stundenplan24.de/10000000/mobil/mobdaten/vpinfok.txt
